### PR TITLE
[Future] Suppose resolve/reject convenience methods

### PR DESCRIPTION
**Pull request by bkotsopoulossc**
It would be nice to have some convenience methods for dealing with futures. 

We often see code like this:
```
::djinni::Future<int> SomeClass::someFunc() {
  // this
  if (!someCondition) {
    ::djinni::Promise<int> promise;
    auto future = promise.getFuture();
    promise.setValue(-1);
    return future;
  }

  // or this
  if (!someCondition) {
    ::djinni::Promise<int> promise;
    auto future = promise.getFuture();
    promise.setException(std::runtime_error("failed"));
    return future;
  }
  
  // or this
  try {
    auto data = getData();
    // ...
  } catch (...) {
    ::djinni::Promise<int> promise;
    auto future = promise.getFuture();
    promise.setException(std::current_exception());
    return future;
  }
}
```

It's a bit verbose, and we can borrow some inspiration from Javascript Promises.

This PR introduces some static convenience methods for returning a future with a value or error.

### CODE REVIEW

**Comment by LiFengSC** [comment]
How about have these methods in the `Future<T>` type instead of `Promise<T>`?

This is because you end up returning an object of `Future<T>`, so IMO it makes sense to have the factory method in `Future<T>`.

**Comment by LiFengSC** [comment]
Otherwise the change looks good and makes sense.

**Comment by bkotsopoulossc** [comment]
We can, we just need to manually create the shared state to create the future. We can hide it all in the static method on the class

**Comment by LiFengSC** [comment]
> We can, we just need to manually create the shared state to create the future. We can hide it all in the static method on the class

Yeah I know we can't just create a future by itself.  I mean we just move these same static methods to the Future<> class because I think it feels more natural from the user's perspective.

**Review by LiFengSC — APPROVED** [review]
Actually,  scrap what I said earlier.  I can see where you come from,  in Javascript the methods are called Promise.resolve() and Promise.reject() so it makes sense to do the same in Promise.

**Pull request merged**
