### PR TITLE
fix typo in generated comment

### PR DESCRIPTION
**Pull request by paulo-coutinho**

### CODE REVIEW

**Comment by finalpatch** [comment]
thank you

**Comment by finalpatch** [comment]
I'm in a bit of dilemma on this one.  On one hand, you are absolutely right this is a typo.  On the other hand,  this will change every single generated file so users will see a massive diff.

**Comment by paulo-coutinho** [comment]
Is better fix now that is in early public stage than after with a lot of people using, this is normal

**Comment by paulo-coutinho** [comment]
We'll merge these changes soon. Having diff is normal and git is for that. If we have to fix something, we will fix it soon.

**Comment by finalpatch** [comment]
@bholmes-sc  what do you think? Should we leave this typo (in comments)  to avoid massive diffs or fix it now?

**Comment by paulo-coutinho** [comment]
> @bholmes-sc what do you think? Should we leave this typo (in comments) to avoid massive diffs or fix it now?

the diff is only is a comment, the users don't have to do nothing

**Review by bholmes-sc — APPROVED** [review]

**Pull request merged**
