### PR TITLE
add support for release

### PR DESCRIPTION
**Pull request by paulo-coutinho**

### CODE REVIEW

**Comment by paulo-coutinho** [comment]
Hi,

I need help here https://github.com/Snapchat/djinni/issues/39 to continue this PR.

Can anyone help?

**Comment by paulo-coutinho** [comment]
Hi, i solved it and appear be OK now. Can anyone review?

**Comment by finalpatch** [comment]
Please take a look at this PR https://github.com/Snapchat/djinni/pull/40 which I want to merge before starting to make release packages

**Comment by finalpatch** [comment]
I'll try to find some time test it in the next few days

**Comment by paulo-coutinho** [comment]
Ok. I see and commented there. It will not impact what i do.

One thing that i can add tomorrow is add the same things for release (djinni, djinni.bat and support-lib.tar.gz) on artifact (each commit) if you want try/test the tools on each commited things before release or only for test something in particular without need release it.

**Comment by finalpatch** [comment]
It would be nice if we could have a script that just generates the release packages locally without uploading them.

**Comment by paulo-coutinho** [comment]
It is already done.

Just run `bazel build //generator:generator`.

And after: "./bazel-bin/generator/djinni" or "./bazel-bin/generator/djinni.bat".

**Comment by finalpatch** [comment]
Thanks!

**Comment by finalpatch** [comment]
I tested the `bazel build //generator:generator` command and the generated binary works on my macbook.
@bholmes-sc could you take a look too?

**Review by benjaminhollissc — APPROVED** [review]
Seems OK to me!

**Review by finalpatch — APPROVED** [review]
Awesome, thank you @paulo-coutinho

**Review by bholmes-sc — COMMENTED** [review]
lgtm

**Pull request merged**
