### PR TITLE
Support optional<> in ObjC containers

### PR DESCRIPTION
**Pull request by LiFengSC**
ObjC containers (NSArray, NSSet, NSDictionary) do not allow `nil` as elements.  However, the codegen does not prevent this, so if C++ puts empty optionals in the container, it will raise as a runtime error in ObjC.

This PR detects empty optional<> in C++ containers, and converts them into `NSNull` objects before returning to ObjC. And converts `NSNull` objects back to empty optionals when they are passed from ObjC to C++.

The check is only performed in containers with optional elements, so the performance of normal containers with non-null elements are unaffected.

### CODE REVIEW

**Comment by paulocoutinhox** [comment]
Nice. Thanks.

**Comment by LiFengSC** [comment]
@bholmes-sc what do you think?

**Comment by paulocoutinhox** [comment]
When you merge it, can you create a new version?

**Review by bholmes-sc — APPROVED** [review]
Change looks good.   Are we able to check this change for any performance impact?

**Comment by LiFengSC** [comment]
> Change looks good. Are we able to check this change for any performance impact?

There is no performance impact when the type is not `optional<>` because the null checked code path is not used.

When the type is `optional<>`, it will null check and this comes with some overhead, but otherwise it won't work correctly anyway (will crash previously if a null is passed).  So performance wise I don't think it regresses in any way.

**Pull request merged**
