### PR TITLE
Force bazel to use d8 instead of dx for Android

### PR DESCRIPTION
**Pull request by LiFengSC**
bazel 5 by default uses dx which is deprecated since 2018 and no longer available in buildtools v31 and later.  This change upgrade bazel version to lates v5 release (5.4.1) and added command line flags to .bazelrc to force it to use d8 instead of dx. The hard coded buildtools version number is removed.

### CODE REVIEW

**Review by bholmes-sc — APPROVED** [review]
We should also plan to upgrade to Bazel 6 soon.

**Comment by LiFengSC** [comment]
> 

IIRC the scala toolchain does not support bazel 6

**Comment by paulocoutinhox** [comment]
https://github.com/bazelbuild/rules_scala#bazel-compatible-versions

**Comment by LiFengSC** [comment]
Tested on Ubuntu with sdk33 & ndk21d.
* build perftest 
* test djinni-java-tests
All good.

**Pull request merged**
